-- Script untuk membuat users di Supabase Auth dan sync ke tabel users
-- 
-- CATATAN: Script ini hanya untuk referensi. 
-- Users HARUS dibuat via Supabase Auth API atau Dashboard terlebih dahulu!
--
-- Cara membuat user:
-- 1. Via Supabase Dashboard:
--    - Buka Authentication → Users → Add User
--    - Isi email dan password
--    - Copy UUID yang diberikan
--
-- 2. Via API (setelah user dibuat):
--    - User akan otomatis tersync ke tabel users saat pertama kali login
--    - Atau insert manual dengan UUID dari Supabase Auth
--
-- 3. Setelah user dibuat di Supabase Auth, gunakan UUID-nya untuk insert ke tabel users:
--
-- INSERT INTO users (id, username, email, password_hash, role) VALUES
-- ('uuid-dari-supabase-auth-1', 'admin', 'admin@perumahan.com', NULL, 'superadmin'),
-- ('uuid-dari-supabase-auth-2', 'manager', 'manager@perumahan.com', NULL, 'admin'),
-- ('uuid-dari-supabase-auth-3', 'staff1', 'staff1@perumahan.com', NULL, 'user'),
-- ('uuid-dari-supabase-auth-4', 'staff2', 'staff2@perumahan.com', NULL, 'user')
-- ON CONFLICT (id) DO NOTHING;
--
-- Untuk mendapatkan UUID, cek di Supabase Dashboard → Authentication → Users

-- Query untuk melihat users yang sudah ada:
-- SELECT id, username, email, role FROM users;